BEGIN;

CREATE TYPE "StaffingPriorityEnum" AS ENUM (
  'FULL_COVERAGE_REQUIRED',
  'TEAM_COVERAGE_REQUIRED',
  'OFFICIAL_COVERAGE_REQUIRED',
  'BEST_AVAILABLE_COVERAGE',
  'FULL_COVERAGE_WITH_CONFLICTS_ALLOWED'
);

ALTER TABLE "Events"
ADD COLUMN "staffingPriority" "StaffingPriorityEnum";

UPDATE "Events"
SET "staffingPriority" = (
  CASE "officialSchedulingMode"
    WHEN 'STAFFING' THEN 'OFFICIAL_COVERAGE_REQUIRED'
    WHEN 'TEAM_STAFFING' THEN 'TEAM_COVERAGE_REQUIRED'
    WHEN 'SCHEDULE' THEN 'BEST_AVAILABLE_COVERAGE'
    WHEN 'OFF' THEN 'FULL_COVERAGE_WITH_CONFLICTS_ALLOWED'
    ELSE 'BEST_AVAILABLE_COVERAGE'
  END
)::"StaffingPriorityEnum";

ALTER TABLE "Events"
ALTER COLUMN "staffingPriority" SET DEFAULT 'BEST_AVAILABLE_COVERAGE',
ALTER COLUMN "staffingPriority" SET NOT NULL;

ALTER TABLE "EventTemplates"
ADD COLUMN "staffingPriority" "StaffingPriorityEnum";

UPDATE "EventTemplates"
SET "staffingPriority" = (
  CASE "officialSchedulingMode"
    WHEN 'STAFFING' THEN 'OFFICIAL_COVERAGE_REQUIRED'
    WHEN 'TEAM_STAFFING' THEN 'TEAM_COVERAGE_REQUIRED'
    WHEN 'SCHEDULE' THEN 'BEST_AVAILABLE_COVERAGE'
    WHEN 'OFF' THEN 'FULL_COVERAGE_WITH_CONFLICTS_ALLOWED'
    ELSE 'BEST_AVAILABLE_COVERAGE'
  END
)::"StaffingPriorityEnum";

ALTER TABLE "EventTemplates"
ALTER COLUMN "staffingPriority" SET DEFAULT 'BEST_AVAILABLE_COVERAGE',
ALTER COLUMN "staffingPriority" SET NOT NULL;

COMMIT;
