// Generated by scripts/sync-shared-icons.mjs. Do not edit manually.

package com.razumly.mvp.icons

import androidx.compose.ui.graphics.vector.ImageVector
import com.razumly.mvp.icons.generated.Images
import com.razumly.mvp.icons.generated.shared.ProductTrophy
import com.razumly.mvp.icons.generated.shared.ProductTournamentBracket
import com.razumly.mvp.icons.generated.shared.ProductGroups

public object SharedIcons {
    public val Trophy: ImageVector
        get() = Images.Shared.ProductTrophy
    public val TournamentBracket: ImageVector
        get() = Images.Shared.ProductTournamentBracket
    public val Groups: ImageVector
        get() = Images.Shared.ProductGroups
}
