import type { Event } from '@/types';

type FixtureOverrides = Record<string, unknown>;

const baseEvent = (overrides: FixtureOverrides = {}): Event => ({
  $id: 'event_editor_fixture',
  id: 'event_editor_fixture',
  name: 'Fixture Event',
  description: 'An event editor round-trip fixture.',
  eventType: 'EVENT',
  sportIds: ['sport_pickleball'],
  start: '2026-09-10T18:00:00.000Z',
  end: '2026-09-10T20:00:00.000Z',
  scheduleEndConstraint: '2026-09-10T20:00:00.000Z',
  generatedScheduleEnd: null,
  noFixedEndDateTime: false,
  timeZone: 'UTC',
  location: 'Main court',
  address: '1 Court Lane',
  coordinates: [40.1, -73.1],
  sourceType: null,
  affiliateUrl: 'https://example.com/fixture',
  parentEvent: null,
  organizationId: null,
  hostId: 'user_fixture_host',
  state: 'UNPUBLISHED',
  imageId: null,
  tags: [{ $id: 'tag_fixture', slug: 'fixture', name: 'Fixture' }],
  teamSignup: false,
  singleDivision: true,
  registrationByDivisionType: false,
  teamSizeLimit: null,
  maxParticipants: 16,
  minAge: null,
  maxAge: null,
  cancellationRefundHours: 24,
  registrationCutoffHours: 2,
  allowTeamSplitDefault: false,
  waitListIds: [],
  freeAgentIds: [],
  price: 0,
  registrationPaymentMode: 'FREE',
  taxHandling: 'INHERIT_ORG',
  organizerManualTaxRateBps: 0,
  manualPaymentLinks: [],
  manualPaymentInstructions: null,
  allowPaymentPlans: false,
  installmentCount: null,
  installmentDueDates: [],
  installmentDueRelativeDays: [],
  installmentAmounts: [],
  divisions: [],
  divisionDetails: [],
  playoffDivisionDetails: [],
  divisionFieldIds: {},
  winnerSetCount: null,
  loserSetCount: null,
  doubleElimination: false,
  includePlayoffs: false,
  splitLeaguePlayoffDivisions: false,
  playoffTeamCount: null,
  pointsToVictory: [11],
  winnerBracketPointsToVictory: [],
  loserBracketPointsToVictory: [],
  usesSets: false,
  setsPerMatch: null,
  setDurationMinutes: null,
  restTimeMinutes: 10,
  matchDurationMinutes: null,
  gamesPerOpponent: 1,
  matchRulesOverride: null,
  leagueScoringConfig: null,
  fields: [{ $id: 'field_fixture', id: 'field_fixture', name: 'Court 1', location: 'Main court' }],
  fieldIds: ['field_fixture'],
  timeSlots: [{
    id: 'slot_fixture',
    $id: 'slot_fixture',
    eventId: 'event_editor_fixture',
    dayOfWeek: 3,
    daysOfWeek: [3],
    startTimeMinutes: 1080,
    endTimeMinutes: 1200,
    repeating: false,
    scheduledFieldIds: ['field_fixture'],
    divisions: [],
  }],
  timeSlotIds: ['slot_fixture'],
  requiredTemplateIds: [],
  immutableFieldIds: [],
  rentalBookingId: null,
  rentalBookingItemId: null,
  requiredDocumentIds: [],
  registrationQuestions: [],
  officialSchedulingMode: 'SCHEDULE',
  doTeamsOfficiate: false,
  teamOfficialsMaySwap: false,
  teamCheckInMode: 'OFF',
  teamCheckInOpenMinutesBefore: 60,
  allowMatchRosterEdits: false,
  allowTemporaryMatchPlayers: false,
  autoCreatePointMatchIncidents: false,
  officialIds: [],
  officialPositions: [],
  eventOfficials: [],
  assistantHostIds: [],
  pendingStaffInvites: [],
  ...overrides,
} as unknown as Event);

const leagueDivision = (id: string, key: string, kind: 'LEAGUE' | 'PLAYOFF' = 'LEAGUE') => ({
  id,
  key,
  name: key === 'open' ? 'Open' : key === 'advanced' ? 'Advanced' : 'Playoffs',
  kind,
  poolPlay: kind === 'LEAGUE' && key === 'advanced',
  divisionTypeId: 'division_type_open',
  skillDivisionTypeId: 'skill_open',
  ageDivisionTypeId: 'age_open',
  divisionTypeName: 'Open',
  ratingType: 'OPEN',
  gender: 'OPEN',
  price: 2500,
  maxParticipants: 16,
  playoffTeamCount: kind === 'PLAYOFF' ? 4 : null,
  poolCount: kind === 'LEAGUE' && key === 'advanced' ? 2 : null,
  poolTeamCount: kind === 'LEAGUE' && key === 'advanced' ? 4 : null,
  phaseSettings: kind === 'PLAYOFF' ? { gamesPerOpponent: 1 } : { gamesPerOpponent: 2 },
  playoffConfig: kind === 'PLAYOFF'
    ? {
      doubleElimination: true,
      winnerSetCount: 3,
      loserSetCount: 2,
      winnerBracketPointsToVictory: [21, 21, 15],
      loserBracketPointsToVictory: [21, 15],
      prize: 'Trophy',
      fieldCount: 2,
      restTimeMinutes: 10,
      matchDurationMinutes: 75,
      setDurationMinutes: 20,
    }
    : null,
  fieldIds: ['field_fixture'],
  teamIds: [],
});

export const eventEditorFixtures = [
  {
    name: 'simple event',
    event: baseEvent(),
  },
  {
    name: 'single-division league',
    event: baseEvent({
      $id: 'event_league_single',
      id: 'event_league_single',
      eventType: 'LEAGUE',
      divisions: ['division_open'],
      divisionDetails: [leagueDivision('division_open', 'open')],
      divisionFieldIds: { division_open: ['field_fixture'] },
    }),
  },
  {
    name: 'multi-division league',
    event: baseEvent({
      $id: 'event_league_multi',
      id: 'event_league_multi',
      eventType: 'LEAGUE',
      singleDivision: false,
      divisions: ['division_open', 'division_advanced'],
      divisionDetails: [leagueDivision('division_open', 'open'), leagueDivision('division_advanced', 'advanced')],
      divisionFieldIds: {
        division_open: ['field_fixture'],
        division_advanced: ['field_fixture'],
      },
    }),
  },
  {
    name: 'tournament with pools and playoffs',
    event: baseEvent({
      $id: 'event_tournament',
      id: 'event_tournament',
      eventType: 'TOURNAMENT',
      teamSignup: true,
      singleDivision: false,
      divisions: ['division_open', 'division_playoffs'],
      divisionDetails: [leagueDivision('division_open', 'open'), leagueDivision('division_playoffs', 'playoffs', 'PLAYOFF')],
      playoffDivisionDetails: [leagueDivision('division_playoffs', 'playoffs', 'PLAYOFF')],
      divisionFieldIds: {
        division_open: ['field_fixture'],
        division_playoffs: ['field_fixture'],
      },
      includePlayoffs: true,
      doubleElimination: true,
      playoffTeamCount: 4,
      winnerSetCount: 2,
      loserSetCount: 1,
    }),
  },
  {
    name: 'weekly event',
    event: baseEvent({
      $id: 'event_weekly',
      id: 'event_weekly',
      eventType: 'WEEKLY_EVENT',
      parentEvent: 'event_weekly_parent',
      timeSlots: [{
        id: 'slot_weekly',
        $id: 'slot_weekly',
        eventId: 'event_weekly',
        dayOfWeek: 4,
        daysOfWeek: [4],
        startTimeMinutes: 1080,
        endTimeMinutes: 1200,
        repeating: true,
        startDate: '2026-09-01',
        endDate: '2026-12-31',
        scheduledFieldIds: ['field_fixture'],
        divisions: [],
      }],
      timeSlotIds: ['slot_weekly'],
    }),
  },
  {
    name: 'organization-hosted paid event',
    event: baseEvent({
      $id: 'event_org_paid',
      id: 'event_org_paid',
      organizationId: 'organization_fixture',
      price: 3500,
      registrationPaymentMode: 'ONLINE',
      taxHandling: 'ORGANIZER_MANUAL',
      organizerManualTaxRateBps: 825,
      allowPaymentPlans: true,
      installmentCount: 2,
      installmentAmounts: [1750, 1750],
    }),
  },
  {
    name: 'rental-backed event',
    event: baseEvent({
      $id: 'event_rental',
      id: 'event_rental',
      organizationId: null,
      rentalBookingId: 'rental_booking_fixture',
      rentalBookingItemId: 'rental_item_fixture',
      requiredTemplateIds: ['template_waiver'],
      immutableFieldIds: ['field_fixture'],
      fields: [{ $id: 'field_fixture', id: 'field_fixture', name: 'Reserved Court', location: 'Facility' }],
    }),
  },
  {
    name: 'team-staffed event',
    event: baseEvent({
      $id: 'event_team_staffed',
      id: 'event_team_staffed',
      teamSignup: true,
      officialSchedulingMode: 'TEAM_STAFFING',
      doTeamsOfficiate: true,
      teamOfficialsMaySwap: true,
      officialPositions: [{ id: 'position_referee', name: 'Referee', count: 2, order: 0 }],
    }),
  },
  {
    name: 'questions and required documents',
    event: baseEvent({
      $id: 'event_questions',
      id: 'event_questions',
      requiredDocumentIds: ['document_waiver', 'document_release'],
      registrationQuestions: [
        {
          id: 'question_existing',
          prompt: 'What is your rating?',
          answerType: 'TEXT',
          required: true,
          sortOrder: 0,
        },
        {
          clientId: 'question_client',
          prompt: 'What should we know?',
          answerType: 'LONG_TEXT',
          required: false,
          sortOrder: 1,
        },
      ],
    }),
  },
] as const;

export type EventEditorFixture = (typeof eventEditorFixtures)[number];
